### ISSUE TITLE
请问是否有key变量

### ISSUE THREAD

**Issue by syscc** [kingmo888/rustdesk-api-server#143]
作者你好
我在docker部署的我尝试配置SECRET_KEY变量为KEY，但是没有作用，是否有其他key的变量？
因为没配置key，在网页端提示key不匹配

**Comment by kingmo888** [comment]
key涉及的是hbbs和hbbr，是你部署服务端的事情。本插件不涉及这个。

**Comment by syscc** [comment]
![image](https://github.com/user-attachments/assets/87eaee10-c12c-41da-985e-5bdd7a17a4b5)
你好，如果在这里设置key才能连接，其他有变量设置过了

**Comment by kingmo888** [comment]
这个中间件也是rustdesk官方的哈。它跟客户端配置一致。但使用它需要非ssl。

**Comment by syscc** [comment]
所以没办法增加这个变量来实现默认key值吗，我看id服务器和api服务器值有变量

**Comment by kingmo888** [comment]
对，这里无法配置。只能使用时配置1次，不过因为有缓存下次使用就不需要配置（就像客户端一样）。
反过来说，如果它能够自动配置，它又是在任何地方可以访问的。那岂不是任何人都可以知道你的这上面的3个配置？
那就成了安全事故了。

**Comment by syscc** [comment]
这个页面一般是登陆用户才能使用，登陆的用户一般都允许使用的，不知道作者能否辛苦下次更新的时候加上这个变量，如果作者应为安全原因不愿意那就算了，给你添麻烦了，感谢你的项目！！！

**Comment by kingmo888** [comment]
官方项目，咱自己加不了。

**Comment by syscc** [comment]
好吧，麻烦你了
