### ISSUE TITLE
我用DOCKER做好构建，可是在起动好后报sh: can't open 'run.sh': No such file or directory

### ISSUE THREAD

**Issue by cq134cq** [kingmo888/rustdesk-api-server#148]
我用DOCKER做好构建，可是在起动好后报sh: can't open 'run.sh': No such file or directory
请问是那里出错了吗

**Comment by cq134cq** [comment]
![image](https://github.com/user-attachments/assets/8feaf734-f1d2-4889-9f53-ff2d15145bac)

**Comment by kingmo888** [comment]
自己构建docker的话，我不太了解。看起来你这目录可能找错了，毕竟提示没找到文件或路径
