### ISSUE TITLE
请问这个apiservice启动后是否能实现注册用户才能使用自己的服务器

### ISSUE THREAD

**Issue by pope-L** [kingmo888/rustdesk-api-server#149]
请问这个apiservice启动后是否能实现注册用户才能使用自己的服务器？
还是所有第三方都无法实现的呢？

**Comment by kingmo888** [comment]
在rustdesk来说，api存在与否不影响客户端与服务端的通信。
api的存在只是与客户端交流了客户端本地所存储的配置云端化。

**Comment by pope-L** [comment]
明白了就是只有 官方pro版才有这样的功能
apiserv只是锦上添花的云端记录
