### ISSUE TITLE
小白求助贴

### ISSUE THREAD

**Issue by 1025766948** [kingmo888/rustdesk-api-server#150]
我的rustdesk服务器地址是远程地址（比如是abc.f3322.net)，而我运行本软件rustdesk-api-server是Windows版电脑，IP地址192.168.1.100，我该如何设置。

**Comment by kingmo888** [comment]
rustdesk-api-server部分填写到API服务器即可。
详细来说，就是假设你通过 http://192.168.1.100:21114 能打开本项目，那就配置该地址 http://192.168.1.100:21114 。
如果，你想要外网访问，也可以像你前面提到的花生壳，为192.168.1.100配置花生壳地址映射（比如 http://myapi.f3322.net:21114 ）。

**Comment by 1025766948** [comment]
非常感谢，成功了，不过我用的是ipv6，运行方式改成了。
python3 /usr/share/rustdesk-api-server-master/manage.py runserver [::]:21114

**Comment by kingmo888** [comment]
> 非常感谢，成功了，不过我用的是ipv6，运行方式改成了。 python3 /usr/share/rustdesk-api-server-master/manage.py runserver [::]:21114

对，根据自身情况做一定变化，完美结局。
祝使用愉快！
