### ISSUE TITLE
Can't login if use any kind of proxy - httpS or socks

### ISSUE THREAD

**Issue by GusevVictor** [kingmo888/rustdesk-api-server#155]
He there, please fix it (tested on v 1.3.0 - 1.3.1 windows client). If I setup any kind of  httpS/socks proxy in that section:

![image](https://github.com/user-attachments/assets/cef27f9e-65c0-4101-b08e-f2ffb952ce9e)

I can see remote desktop but can't login and see address book also.

![image](https://github.com/user-attachments/assets/6068366e-a134-4c48-abd5-c82f81d01a56)

Best regards for any help.

**Comment by kingmo888** [comment]
Yes, the proxy part is currently not being tested.

**Comment by GusevVictor** [comment]
> Yes, the proxy part is currently not being tested.

I will glad if you can fix that because it's important to use that for block users which is no longer belong to work team.

**Comment by GusevVictor** [comment]
Dear @kingmo888 for implement this I think that you need to implement api witch is allow to connect only by tcp mode. It's avalible only in real PRO version.

**Comment by kingmo888** [comment]
> Dear @kingmo888 for implement this I think that you need to implement api witch is allow to connect only by tcp mode. It's avalible only in real PRO version.亲爱的 @kingmo888，为了实现这一点，我认为您需要实现仅允许通过 tcp 模式连接的 api。它仅在真正的 PRO 版本中可用。

We may have a misunderstanding about the agent.
Even if the proxy mode requires an account or password, it should not block communication between the client and server.
In other words, after configuring the proxy, you intercepted the communication between the client and the server. However, if a client that already knows the server information does not configure the proxy information, cannot it access the server? It's not true.

**Comment by GusevVictor** [comment]
> > Dear @kingmo888 for implement this I think that you need to implement api witch is allow to connect only by tcp mode. It's avalible only in real PRO version.亲爱的 @kingmo888，为了实现这一点，我认为您需要实现仅允许通过 tcp 模式连接的 api。它仅在真正的 PRO 版本中可用。
> 
> We may have a misunderstanding about the agent. Even if the proxy mode requires an account or password, it should not block communication between the client and server. In other words, after configuring the proxy, you intercepted the communication between the client and the server. However, if a client that already knows the server information does not configure the proxy information, cannot it access the server? It's not true.

There is not to so easy but now I can login. There is very strange but true: client use login and password proxy only when try to connect to hbbs / hbbr but it's not use proxy login and password during connect to web API. For fix that a just allow login to api port 2114/443 without any login. So, I can login to the API but still can't change my connect state to online because you need to implement tcp mode API I think.

Best regards.

**Comment by kingmo888** [comment]
TCP functionality is currently not within the scope of the project.
