### ISSUE TITLE
请问一直启动不起来是可能哪几种情况？

### ISSUE THREAD

**Issue by kuufuucom** [kingmo888/rustdesk-api-server#157]
你好，刚开始安装的时候可以正常启动。后来他自己关闭了启动页面，我去手动启动怎么都启动不起来
还有就是网页控制提示key不匹配       服务端是自动生成的key

**Comment by kuufuucom** [comment]
![Uploading Snipaste_2024-11-01_16-25-06.jpg…]()

**Comment by kuufuucom** [comment]
![Snipaste_2024-11-01_16-25-06](https://github.com/user-attachments/assets/ae7eeb52-1d23-48f4-9767-3b55f9c6e3b1)

**Comment by kingmo888** [comment]
应该是遇到错误崩溃了。绿色版很久没更了，版本可能跟不上。
