### ISSUE TITLE
能否实现用户设备数量限制

### ISSUE THREAD

**Issue by yundazhe** [kingmo888/rustdesk-api-server#162]
请问，有什么办法限制用户数量吗？还有限制用户最大带宽？

**Comment by kingmo888** [comment]
“请问，有什么办法限制用户数量吗？”
在web api上可以伪限制，即只记录多少个数据，多的不返回。但客户端如果压根不去分享，只自用，哪怕没有web api他也正常用。因为这是服务端干的活。

“还有限制用户最大带宽？”
这也是服务端干的活。

**Comment by timiil** [comment]
请问哪一个API提供我们查询当前用户数量，受控设备数量？

**Comment by kingmo888** [comment]
汇总管理页就是的。
客户端上报当前账号下peer，然后本工具将其汇总了。可下载xlsx
