### ISSUE TITLE
CSRF验证失败. 请求被中断.

### ISSUE THREAD

**Issue by ferocknew** [kingmo888/rustdesk-api-server#3]
通过 ip:端口 没有问题，域名 反向代理有问题

![5b60694ce9002cc4ddba69e112b79684](https://github.com/kingmo888/rustdesk-api-server/assets/2178683/f6760e6e-8461-466f-a4db-0c8304d9b6ad)

**Comment by ferocknew** [comment]
请求地址，添加用户的 post
/admin/api/userprofile/add/

**Comment by quarkape** [comment]
请问不是docker的方案，怎么解决？
------
需要删除的时候用ip+端口登录，解决，主打一个粗暴。
