### ISSUE TITLE
[Bug]: api 登陆后 地址簿错误 返回code: 102, data:“\u66f4\u65b0\u5730\u5740\u7c3f\u6709\u8bef"

### ISSUE THREAD

**Issue by jsrcode** [kingmo888/rustdesk-api-server#40]
### What happened?

code: 102, data:“\u66f4\u65b0\u5730\u5740\u7c3f\u6709\u8bef"
经过测试应该是程序问题，如果在后台把token删除就可以正常使用，重新登录刷新token后就102错误了

### Operation System

win11

### Python Version

3.9

### Run type Python/Docker

Docker

**Comment by Sunev** [comment]
是否使用 x86-sciter 版客户端？
可以参考刚提的pr https://github.com/kingmo888/rustdesk-api-server/pull/41

**Comment by jsrcode** [comment]
是的，我使用的是x86-sciter版本的客户端
