### ISSUE TITLE
WebUI attempts to use ws instead of a wss connection on https

### ISSUE THREAD

**Issue by 1-tempest** [kingmo888/rustdesk-api-server#68]
It seems that the websockets being used are only ws. If I attempt to use a secure connection (https), it requires that the websocket is wss.

**Comment by khat17** [comment]
You got it working? I can't get it to work with my self-hosted instance.

I tried the different options listed below. Let me know what I did wrong please. 

ID_SERVER = os.environ.get("ID_SERVER", 'myhost.com')
ID_SERVER = os.environ.get("myhost.com')
ID_SERVER = 'myhost.com'
ID_SERVER = ("ID_SERVER", 'myhost.com')
ID_SERVER = ("myhost.com")

**Comment by MIKU-N** [comment]
> That's the issue, one version will not work for both. This needs to be a variable within the setup, or add some logic to modify it to `ws` or `wss` based on if the string is `http` or `https`.
> 
> If you make the url `https://` then we need it to be `wss://`, however if the url is `http://` then we need it to be `ws://`.
> 
> @kingmo888 my apologies, I didn't get a notification to your response

I test your idea,But it's not work now beacuse rustdesk websocket server not support wss...
Look like they don't want to add it...
- https://github.com/rustdesk/rustdesk/discussions/6023#discussioncomment-8687562
- https://github.com/rustdesk/rustdesk-server/discussions/352
