### ISSUE TITLE
最近开始出现了key不匹配，无法链接

### ISSUE THREAD

**Issue by kokojacket** [kingmo888/rustdesk-api-server#83]
![image](https://github.com/kingmo888/rustdesk-api-server/assets/74887370/56010812-a12b-40a7-b62c-1136165b6d94)

**Comment by kokojacket** [comment]
似乎是新版的hbbs默认强制生成了key，在.pub文件下看见了key，填入后可以链接了。就是不知道怎么不生成key了。。。

**Comment by kokojacket** [comment]
已解决：
This version changes default -k of hbbs to -, which means setting key on client side is mandatory. If you want to run empty -k as before, please run hbbs -k ""。
该版本将hbbs的默认值-k更改为-，这意味着客户端必须设置key。 如果您想像以前一样运行空-k，请运行hbbs -k ""。

**Comment by makehistory6** [comment]
有一个可能是重复安装，先把所有相关的先清除一遍，再安装就可以了

**Comment by ch-boogeyman** [comment]
> 有一个可能是重复安装，先把所有相关的先清除一遍，再安装就可以了

怎么彻底清理，卸载后rust的目录已经消失了，重新安装还是提示key不匹配，我后端是换了一台服务器的。
